name: Test
on:
- push
jobs:
  test_xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery
  test_bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery
  test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
    - run: swift test --enable-test-discovery